const fs = require('fs');

const missingEn = {
  "recharge": "Recharge",
  "user": "User",
  "amount": "Amount",
  "confirm_payment": "Confirm Payment",
  "transactions": "Transactions",
  "commission_balance": "Commission Balance",
  "test_name": "Test Name",
  "redirect": "Redirect",
  "email": "Email",
  "role": "Role",
  "room": "Room",
  "script": "Script",
  "clinic_setup": "Clinic Setup",
  "clinic_setup_desc": "Manage your clinical environment settings",
  "patient_care_plus": "Patient Care Plus",
  "patient_care_plus_desc": "Advanced tracking for high-priority patients",
  "emergency_contacts": "Emergency Contacts",
  "identity_verification": "Identity Verification",
  "action_required": "Action Required",
  "delete": "Delete",
  "delete_account": "Delete Account",
  "ai_assisted_specialist": "AI Assisted Specialist",
  "trigger_emergency": "Trigger Emergency",
  "tele_health": "TeleHealth",
  "lab_interpreter": "Lab Interpreter",
  "symptom_checker": "Symptom Checker",
  "wearables": "Wearable Integration",
  "prescriptions": "Prescriptions",
  "prescription_ai": "Prescription AI",
  "ambulance_service": "Ambulance Transport",
  "vaccination_tracker": "Vaccines & Immunization",
  "blood_hub": "Blood Hub Registry",
  "organ_donation": "Organ Donation Network",
  "appointment_optimizer": "Smart AI Appointments",
  "medicine_inventory": "Smart Inventory",
  "join_user_room": "Join Collaborative Room",
  "transaction_failed": "Transaction Failed",
  "driver_dashboard": "Driver Dispatch Dashboard",
  "trigger_sos": "Immediate SOS Protocol",
  "rider_dashboard": "Medical Rider Navigation",
  "recommended_action": "Recommended Action",
  "urgent": "Urgent",
  "normal": "Normal",
  "emergency": "Emergency",
  "on_active_mission": "On Active Mission",
  "available_for_dispatch": "Available for Dispatch",
  "active_mission": "Active Mission",
  "loading_queue": "Loading Queue...",
  "no_patients_in_queue": "No patients in queue",
  "unknown_patient": "Unknown Patient",
  "general": "General",
  "driver_location_update": "Location Update Sent",
  "rider_location_update": "Logistics Update Sent",
  "medical_delivery": "Medical Delivery Protocol"
};

const missingZh = {
  "recharge": "充值",
  "user": "用户",
  "amount": "金额",
  "confirm_payment": "确认付款",
  "transactions": "交易记录",
  "commission_balance": "佣金余额",
  "test_name": "测试名称",
  "redirect": "重定向",
  "email": "电子邮件",
  "role": "角色",
  "room": "房间",
  "script": "脚本",
  "clinic_setup": "诊部设置",
  "clinic_setup_desc": "管理您的临床环境设置",
  "patient_care_plus": "患者护理+计划",
  "patient_care_plus_desc": "针对高优先级患者的高级跟踪",
  "emergency_contacts": "紧急联系人",
  "identity_verification": "身份验证",
  "action_required": "待办事项",
  "delete": "删除",
  "delete_account": "删除账户",
  "ai_assisted_specialist": "AI辅助专家",
  "trigger_emergency": "触发紧急警报",
  "tele_health": "互联网医疗通话",
  "lab_interpreter": "实验室报告AI解读",
  "symptom_checker": "AI症状自查",
  "wearables": "物联网穿戴设备集成",
  "prescriptions": "电子处方流转",
  "prescription_ai": "AI处方分析",
  "ambulance_service": "救护车联合调度",
  "vaccination_tracker": "疫苗与免疫记录",
  "blood_hub": "区域血液中心资源",
  "organ_donation": "器官捐献与匹配网络",
  "appointment_optimizer": "智能AI预约优化",
  "medicine_inventory": "智能耗材库存",
  "join_user_room": "加入协同数字病房",
  "transaction_failed": "交易失败",
  "driver_dashboard": "司机调度仪表板",
  "trigger_sos": "立即触发SOS急救协议",
  "rider_dashboard": "医疗专送骑手导航",
  "recommended_action": "推荐行动方案",
  "urgent": "紧急",
  "normal": "普通",
  "emergency": "抢救",
  "on_active_mission": "正在执行任务",
  "available_for_dispatch": "可供调度",
  "active_mission": "活动任务",
  "loading_queue": "正在加载队列...",
  "no_patients_in_queue": "队列中没有患者",
  "unknown_patient": "未知患者",
  "general": "普通科",
  "driver_location_update": "位置更新已发送",
  "rider_location_update": "物流更新已发送",
  "medical_delivery": "医疗专送协议"
};

let i18nContent = fs.readFileSync('src/i18n.ts', 'utf8');

const enInsertIdx = i18nContent.indexOf('en: {\n    translation: {') + 'en: {\n    translation: {'.length;
let enEntries = Object.entries(missingEn).map(([k, v]) => `\n      "${k}": ${JSON.stringify(v)},`).join('');

i18nContent = i18nContent.slice(0, enInsertIdx) + enEntries + i18nContent.slice(enInsertIdx);

const zhInsertIdx = i18nContent.indexOf('zh: {\n    translation: {') + 'zh: {\n    translation: {'.length;
let zhEntries = Object.entries(missingZh).map(([k, v]) => `\n      "${k}": ${JSON.stringify(v)},`).join('');

i18nContent = i18nContent.slice(0, zhInsertIdx) + zhEntries + i18nContent.slice(zhInsertIdx);

fs.writeFileSync('src/i18n.ts', i18nContent);
console.log('Successfully injected missing features i18n keys!');
